site_name: Pen programming language
site_url: https://pen-lang.org/
repo_url: https://github.com/pen-lang/pen
strict: true
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: README.md
  - Install: introduction/install.md
  - Getting started: introduction/getting-started.md
  - Guides:
      - Building an executable: guides/building-an-executable.md
      - Creating a library: guides/creating-a-library.md
      - Using a library: guides/using-a-library.md
      - Testing: guides/testing.md
      - Concurrency and parallelism: guides/concurrency-and-parallelism.md
      - Coding style: guides/coding-style.md
      - Advanced features:
          - Cross compile: advanced-features/cross-compile.md
          - Foreign Function Interface (FFI): advanced-features/ffi.md
          - Writing system packages: advanced-features/writing-system-packages.md
  - References:
      - Language:
          - Syntax: references/language/syntax.md
          - Types: references/language/types.md
          - Built-ins: references/language/built-ins.md
          - Modules: references/language/modules.md
          - Packages: references/language/packages.md
      - Command line tools: references/command-line-tools.md
      - Standard packages:
          - Core: references/standard-packages/core.md
          - Flag: references/standard-packages/flag.md
          - Json: references/standard-packages/json.md
          - Html: references/standard-packages/html.md
          - Http: references/standard-packages/http.md
          - Os: references/standard-packages/os.md
          - Random: references/standard-packages/random.md
          - Regex: references/standard-packages/regex.md
          - Sql: references/standard-packages/sql.md
          - Test: references/standard-packages/test.md
  - Examples:
      - Types:
          - Number: examples/types/number.md
          - Boolean: examples/types/boolean.md
          - None: examples/types/none.md
          - String: examples/types/string.md
          - Function: examples/types/function.md
          - Record: examples/types/record.md
          - Union: examples/types/union.md
          - List: examples/types/list.md
          - Error: examples/types/error.md
          - Any: examples/types/any.md
          - Polymorphism: examples/types/polymorphism.md
      - Syntax:
          - Block: examples/syntax/block.md
      - Modules: examples/module.md
      - Packages: examples/package.md
      - Commands:
          - Building packages: examples/commands/build.md
          - Creating packages: examples/commands/create.md
          - Testing packages: examples/commands/test.md
          - Formatting module files: examples/commands/format.md
      - Standard packages:
          - Core: examples/standard-packages/core.md
          - Os: examples/standard-packages/os.md
          - Random: examples/standard-packages/random.md
          - Test: examples/standard-packages/test.md
      - Foreign Function Interface (FFI): examples/ffi.md
  - Roadmap: roadmap.md
  - The Zen: the-zen.md
